//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="RuleWsImplPortBinding", Namespace="http://impl.ws.icollection.com/")]
public partial class SlmRuleService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback executeRuleSmsOperationCompleted;
    
    /// <remarks/>
    public SlmRuleService() {
        //this.Url = "http://10.3.112.46:8080/SlmRuleWs/SlmRuleService";
        this.Url = System.Configuration.ConfigurationManager.AppSettings["SlmRuleServiceUrl"].ToString();
    }
    
    /// <remarks/>
    public event executeRuleSmsCompletedEventHandler executeRuleSmsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://impl.ws.icollection.com/", ResponseNamespace="http://impl.ws.icollection.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string executeRuleSms([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string request) {
        object[] results = this.Invoke("executeRuleSms", new object[] {
                    request});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginexecuteRuleSms(string request, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("executeRuleSms", new object[] {
                    request}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndexecuteRuleSms(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void executeRuleSmsAsync(string request) {
        this.executeRuleSmsAsync(request, null);
    }
    
    /// <remarks/>
    public void executeRuleSmsAsync(string request, object userState) {
        if ((this.executeRuleSmsOperationCompleted == null)) {
            this.executeRuleSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteRuleSmsOperationCompleted);
        }
        this.InvokeAsync("executeRuleSms", new object[] {
                    request}, this.executeRuleSmsOperationCompleted, userState);
    }
    
    private void OnexecuteRuleSmsOperationCompleted(object arg) {
        if ((this.executeRuleSmsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.executeRuleSmsCompleted(this, new executeRuleSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void executeRuleSmsCompletedEventHandler(object sender, executeRuleSmsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class executeRuleSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal executeRuleSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
