//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLM.Application.LeadServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://schemas.datacontract.org/2004/07/SLS.Service")]
    [System.SerializableAttribute()]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelID {
            get {
                return this.ChannelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelIDField, value) != true)) {
                    this.ChannelIDField = value;
                    this.RaisePropertyChanged("ChannelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Encoding {
            get {
                return this.EncodingField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodingField, value) != true)) {
                    this.EncodingField = value;
                    this.RaisePropertyChanged("Encoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeadServiceProxy.ILeadService")]
    public interface ILeadService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (www.kiatnakinbank.com/services/SlmLeadService/InsertLead) of message InsertLeadRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadService/InsertLead", ReplyAction="http://tempuri.org/ILeadService/InsertLeadResponse")]
        SLM.Application.LeadServiceProxy.InsertLeadResponse InsertLead(SLM.Application.LeadServiceProxy.InsertLeadRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (www.kiatnakinbank.com/services/SlmLeadService/UpdateLead) of message UpdateLeadRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadService/UpdateLead", ReplyAction="http://tempuri.org/ILeadService/UpdateLeadResponse")]
        SLM.Application.LeadServiceProxy.UpdateLeadResponse UpdateLead(SLM.Application.LeadServiceProxy.UpdateLeadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertLeadRequest", WrapperNamespace="www.kiatnakinbank.com/services/SlmLeadService/InsertLead", IsWrapped=true)]
    public partial class InsertLeadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="www.kiatnakinbank.com/services/SlmLeadService/InsertLead")]
        public SLM.Application.LeadServiceProxy.Header RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/SlmLeadService/InsertLead", Order=0)]
        public string RequestXml;
        
        public InsertLeadRequest() {
        }
        
        public InsertLeadRequest(SLM.Application.LeadServiceProxy.Header RequestHeader, string RequestXml) {
            this.RequestHeader = RequestHeader;
            this.RequestXml = RequestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertLeadResponse", WrapperNamespace="www.kiatnakinbank.com/services/SlmLeadService/InsertLead", IsWrapped=true)]
    public partial class InsertLeadResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="www.kiatnakinbank.com/services/SlmLeadService/InsertLead")]
        public SLM.Application.LeadServiceProxy.Header ResponseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/SlmLeadService/InsertLead", Order=0)]
        public string ResponseStatus;
        
        public InsertLeadResponse() {
        }
        
        public InsertLeadResponse(SLM.Application.LeadServiceProxy.Header ResponseHeader, string ResponseStatus) {
            this.ResponseHeader = ResponseHeader;
            this.ResponseStatus = ResponseStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLeadRequest", WrapperNamespace="www.kiatnakinbank.com/services/SlmLeadService/UpdateLead", IsWrapped=true)]
    public partial class UpdateLeadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="www.kiatnakinbank.com/services/SlmLeadService/UpdateLead")]
        public SLM.Application.LeadServiceProxy.Header RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/SlmLeadService/UpdateLead", Order=0)]
        public string RequestXml;
        
        public UpdateLeadRequest() {
        }
        
        public UpdateLeadRequest(SLM.Application.LeadServiceProxy.Header RequestHeader, string RequestXml) {
            this.RequestHeader = RequestHeader;
            this.RequestXml = RequestXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLeadResponse", WrapperNamespace="www.kiatnakinbank.com/services/SlmLeadService/UpdateLead", IsWrapped=true)]
    public partial class UpdateLeadResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="www.kiatnakinbank.com/services/SlmLeadService/UpdateLead")]
        public SLM.Application.LeadServiceProxy.Header ResponseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.kiatnakinbank.com/services/SlmLeadService/UpdateLead", Order=0)]
        public string ResponseStatus;
        
        public UpdateLeadResponse() {
        }
        
        public UpdateLeadResponse(SLM.Application.LeadServiceProxy.Header ResponseHeader, string ResponseStatus) {
            this.ResponseHeader = ResponseHeader;
            this.ResponseStatus = ResponseStatus;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeadServiceChannel : SLM.Application.LeadServiceProxy.ILeadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeadServiceClient : System.ServiceModel.ClientBase<SLM.Application.LeadServiceProxy.ILeadService>, SLM.Application.LeadServiceProxy.ILeadService {
        
        public LeadServiceClient() {
        }
        
        public LeadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SLM.Application.LeadServiceProxy.InsertLeadResponse SLM.Application.LeadServiceProxy.ILeadService.InsertLead(SLM.Application.LeadServiceProxy.InsertLeadRequest request) {
            return base.Channel.InsertLead(request);
        }
        
        public SLM.Application.LeadServiceProxy.Header InsertLead(SLM.Application.LeadServiceProxy.Header RequestHeader, string RequestXml, out string ResponseStatus) {
            SLM.Application.LeadServiceProxy.InsertLeadRequest inValue = new SLM.Application.LeadServiceProxy.InsertLeadRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.RequestXml = RequestXml;
            SLM.Application.LeadServiceProxy.InsertLeadResponse retVal = ((SLM.Application.LeadServiceProxy.ILeadService)(this)).InsertLead(inValue);
            ResponseStatus = retVal.ResponseStatus;
            return retVal.ResponseHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SLM.Application.LeadServiceProxy.UpdateLeadResponse SLM.Application.LeadServiceProxy.ILeadService.UpdateLead(SLM.Application.LeadServiceProxy.UpdateLeadRequest request) {
            return base.Channel.UpdateLead(request);
        }
        
        public SLM.Application.LeadServiceProxy.Header UpdateLead(SLM.Application.LeadServiceProxy.Header RequestHeader, string RequestXml, out string ResponseStatus) {
            SLM.Application.LeadServiceProxy.UpdateLeadRequest inValue = new SLM.Application.LeadServiceProxy.UpdateLeadRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.RequestXml = RequestXml;
            SLM.Application.LeadServiceProxy.UpdateLeadResponse retVal = ((SLM.Application.LeadServiceProxy.ILeadService)(this)).UpdateLead(inValue);
            ResponseStatus = retVal.ResponseStatus;
            return retVal.ResponseHeader;
        }
    }
}
